name: BCAG
favicon: null
layout_spectrum: 0
typography_spectrum: 0.77104
title: BCAG - Brendon Chen Alta Gioielleria
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#959595'
    - '#6b6b6b'
    - '#5c3929'
  brandStrength: 0.4571461013983935
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
